workspaces/DC Dev/DC Dev/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <label>Active</label>
        <picklist>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Email_Address__c</fullName>
        <label>Email Address</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Primary_Contact__c</fullName>
        <description>Holds the mail address of the primary contact.</description>
        <label>Primary Contact</label>
        <type>Email</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

workspaces/DC Dev/DC Dev/src/objects/Event__c.object
<CustomObject>
    <description>Holds the JSON of the records that need to be processed.</description>
    <fields>
        <fullName>JSON__c</fullName>
        <description>Holds the actual JSON.</description>
        <label>JSON</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Processed__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Checked to true  once the JSON is processed and the records are created.</description>
        <label>Processed?</label>
        <type>Checkbox</type>
    </fields>
    <label>Event</label>
    <nameField>
        <label>Object Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

workspaces/DC Dev/DC Dev/src/classes/TestJsonToRecordCreator.cls
@isTest
private class TestJsonToRecordCreator {

    static testMethod void TestPositive() {

        JsonToRecordCreator JtrcInstance = new JsonToRecordCreator();
        Event__c event = new Event__c(
            JSON__c = '{ "Name" : "Dnyanesh", "Email_Address__c" : "dnyanesh.chandratre@eternus.com", "Primary_Contact__c" : "dnyanesh@eternussolutions.com", "Active__c": "Yes", "Phone" : "546548975"}',
            Name = 'Account',
            Processed__c = false
        );
        insert event;

        Test.startTest();
        Database.executeBatch(JtrcInstance,5);
        Test.stopTest();

        list<Event__c> listEvent = [SELECT Id,Name,JSON__c,Processed__c FROM Event__c WHERE Processed__c = true];
        system.debug('******************ListEVENT***************'+listEvent);
        
        system.assertEquals(1,listEvent.size());
    }

    static testMethod void TestNegative() {

        JsonToRecordCreator JtrcInstance = new JsonToRecordCreator();
        Event__c event = new Event__c(
            JSON__c = '{ "Name" : "Dnyanesh", "Email_Address__c" : "dnyanesh.chandratre@eternus.com", "Primary_Contact__c" : "dnyanesh@eternussolutions.com", "Active__c": "Yes", "Phone" : "546548975"}',
            Name = 'Accounts',
            Processed__c = false
        );

        insert event;

        Test.startTest();
        Database.executeBatch(JtrcInstance,5);
        Test.stopTest();

        list<Event__c> listEvent = [SELECT Id,Name,JSON__c,Processed__c FROM Event__c WHERE Processed__c = true];
        system.debug('******************ListEVENT***************'+listEvent);
        
        system.assertNotEquals(1,listEvent.size());
    }
}