workspaces/DC Dev/DC Dev/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Email_Address__c</fullName>
        <label>Email Address</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>PersonEmail__c</fullName>
        <label>Person Email</label>
        <type>Email</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

workspaces/DC Dev/DC Dev/src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Supplied_Mail__c</fullName>
        <description>Provide custom supplied mail.</description>
        <label>Supplied Mail</label>
        <type>Email</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

workspaces/DC Dev/DC Dev/src/classes/caseUpdationTest.cls
/**
 *  Title       : Test class for handler class of CaseUpdateTrigger
 *  Class       : caseUpdationTest
 *  Author      : Dnyanesh Chandratre
 *  Created On  :  7/20/2015
 */

@isTest
public class caseUpdationTest {

    /*Testing Both Email Match Case*/
    static testMethod void matchBothEmails() {
        Account objAccount = new Account(
            Name = 'Foo',
            PersonEmail__c='a@b.com',
            Email_Address__c = 'a@b.com'
        );

        insert objAccount;
        insert new Contact(LastName = 'TriggerTest',AccountId = objAccount.Id);

        Case objCase = new Case();
        objCase.Origin = 'Web';
        objCase.Status = 'New';
        objCase.Supplied_Mail__c = 'a@b.com';

        test.startTest();
        insert objCase;
        test.stopTest();

        objCase = [SELECT AccountId FROM Case];
        System.assertEquals(objAccount.Id, objCase.AccountId);
    }
    
    /*Testing Single Email Match Case [1]*/
    static testMethod void matchEmailAddress() {
        Account objAccount = new Account(
            Name = 'Foo',
            PersonEmail__c='x@y.com',
            Email_Address__c = 'a@b.com'
        );

        insert objAccount;
        insert new Contact(LastName = 'TriggerTest', AccountId = objAccount.Id);

        Case objCase = new Case();
        objCase.Origin = 'Email';
        objCase.Status = 'New';
        objCase.Supplied_Mail__c = 'a@b.com';

        test.startTest();
        insert objCase;
        test.stopTest();

        objCase = [SELECT AccountId FROM Case];
        System.assertEquals(objAccount.Id, objCase.AccountId);
    }
    
    /*Testing Single Email Match Case [2]*/
    static testMethod void matchPersonEmail() {
        Account objAccount = new Account(
            Name = 'Foo',
            PersonEmail__c='a@b.com',
            Email_Address__c = 'x@y.com'
        );

        insert objAccount;
        insert new Contact(LastName = 'TriggerTest',AccountId = objAccount.Id);

        Case objCase = new Case();
        objCase.Origin = 'Phone';
        objCase.Status = 'New';
        objCase.Supplied_Mail__c = 'a@b.com';

        test.startTest();
        insert objCase;
        test.stopTest();

        objCase = [SELECT AccountId FROM Case];
        System.assertEquals(objAccount.Id,objCase.AccountId);
    }

    /*Testing No Email Match Case [2]*/
    static testMethod void matchNoEmails() {
        Account objAccount = new Account(
            Name = 'Foo',
            PersonEmail__c='x@y.com',
            Email_Address__c = 'c@d.com'
        );

        insert objAccount;
        insert new Contact(LastName = 'TriggerTest',AccountId = objAccount.Id);

        Case objCase = new Case();
        objCase.Origin = 'Web';
        objCase.Status = 'New';
        objCase.Supplied_Mail__c = 'a@b.com';

        test.startTest();
        insert objCase;
        test.stopTest();

        objCase = [SELECT AccountId FROM Case];
        System.assertEquals(NULL,objCase.AccountId);
    }
}