workspaces/DC Dev/DC Dev/src/objects/City__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Holds the list of cities</description>
    <fields>
        <fullName>Country__c</fullName>
        <description>Holds the country of the city.</description>
        <label>Country</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>City</label>
</CustomObject>

workspaces/DC Dev/DC Dev/src/objects/Country__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Holds a list of countries.</description>
    <label>Country</label>
</CustomObject>

workspaces/DC Dev/DC Dev/src/classes/CitySelectController.cls
public with sharing class CitySelectController {

    public String selectedCountry              {get; set;}
    public string selectedCity                 {get; set;}
    public List<SelectOption> countryPickList  {get; set;}
    public List<selectOption> cityPickList     {get; set;}

    public void init() {
        populateCountryPickList();
    }

    public List<SelectOption> populateCountryPickList() {

        countryPickList = new List<SelectOption>();

        countryPickList.add( new SelectOption(
                'NULL',
                '--- Select Country ---'
            ));

        for (Country__c countryInstance : Country__c.getAll().Values()) {

            countryPickList.add( new SelectOption(
                countryInstance.Name,
                countryInstance.Name
            ));
        }

        return countryPickList;
    }

    public void populateCityPickList() {
        cityPickList = new List<SelectOption>();
        for (City__c cityInstance : [
            SELECT Name 
              FROM City__c
             WHERE Country__c = :selectedCountry
        ]) {
            cityPickList.add( new SelectOption(
                cityInstance.Name,
                cityInstance.Name
            ));
        }
    }
}